spring:
  profiles:
    active: dev
  application:
    name: gmbyte-cms
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    solr:
      host: http://127.0.0.1:8983/solr/

  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    template-loader-path: file:WEB-INF/,file:WEB-INF/manager,classpath:/,classpath:/WEB-INF/manager,classpath:/WEB-INF
    settings:
      template_update_delay: 1
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##

server:
  port: 8081
  max-http-header-size: 81920
